// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZs1Svb27bfrVmc9cSyrSQ9u2fOlUIJjg',
    // apiKey: dotenv.env['API_KEY_web']!,
    appId: '1:478441637613:web:bd7e4624038d97629caee4',
    messagingSenderId: '478441637613',
    projectId: 'taskflow-445df',
    authDomain: 'taskflow-445df.firebaseapp.com',
    storageBucket: 'taskflow-445df.appspot.com',
    measurementId: 'G-YRM342SFL7',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0VSY9QvXJAzxaqcTSmM-Rl65Vuoxq80',
    // apiKey: dotenv.env['API_KEY_iOS']!,
    appId: '1:478441637613:ios:d41f972603e13fcc9caee4',
    messagingSenderId: '478441637613',
    projectId: 'taskflow-445df',
    storageBucket: 'taskflow-445df.appspot.com',
    iosBundleId: 'com.example.timesphere',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0VSY9QvXJAzxaqcTSmM-Rl65Vuoxq80',
    // apiKey: dotenv.env['API_KEY_macOS']!,
    appId: '1:478441637613:ios:d41f972603e13fcc9caee4',
    messagingSenderId: '478441637613',
    projectId: 'taskflow-445df',
    storageBucket: 'taskflow-445df.appspot.com',
    iosBundleId: 'com.example.timesphere',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZs1Svb27bfrVmc9cSyrSQ9u2fOlUIJjg',
    // apiKey: dotenv.env['API_KEY_windows']!,
    appId: '1:478441637613:web:bd7e4624038d97629caee4',
    messagingSenderId: '478441637613',
    projectId: 'taskflow-445df',
    authDomain: 'taskflow-445df.firebaseapp.com',
    storageBucket: 'taskflow-445df.appspot.com',
    measurementId: 'G-YRM342SFL7',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi1nY-IaR247P_qbH8R4m7MwT5RBwoPxE' ,
    // apiKey: dotenv.env['API_KEY_Android']! ,
    appId: '1:478441637613:android:bdbb983e3b1b0f879caee4',
    messagingSenderId: '478441637613',
    projectId: 'taskflow-445df',
    storageBucket: 'taskflow-445df.appspot.com',
  );

}